name: CI

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 26
          elixir-version: 1.16
      - run: mix format --check-formatted
      - run: mix compile --warnings-as-errors
